# Site settings
title: NetPonto | A Comunidade .NET em Portugal
email: contacto@netponto.org
description: > # this means to ignore newlines until "baseurl:"
  A comunidade NetPonto é uma iniciativa independente e sem fins lucrativos, 
  que tem como simples e único objectivo a partilha de conhecimento na área de 
  arquitectura e desenvolvimento de software na plataforma .NET, na tentativa 
  de disseminar o conhecimento diferenciado de cada um de seus membros.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://netponto.github.io" # the base hostname & protocol for your site

# GitHub Pages settings
repository: netponto/netponto.github.io

# Build settings
safe: true
markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock

show_drafts: false
future: false

permalink: /:categories/:title/

defaults:
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      draft: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "_posts/sessoes"
      type: "posts"
    values:
      categories: sessao

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
