# _config-local.yml - Local dev environment configs and overrides

# Site settings
url: "http://127.0.0.1:4096" # the base hostname & protocol for your site

# Build settings
show_drafts: true
future: true

# Don't compress SASS output
sass:
  style: full
