title: NetPonto | A Comunidade .NET em Portugal
email: contacto@netponto.org
description: > # this means to ignore newlines until "baseurl:"
  A comunidade NetPonto é uma iniciativa independente e sem fins lucrativos, 
  que tem como simples e único objectivo a partilha de conhecimento na área de 
  arquitectura e desenvolvimento de software na plataforma .NET, na tentativa 
  de disseminar o conhecimento diferenciado de cada um de seus membros.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://netponto.github.io" # the base hostname & protocol for your site
relative_permalinks: false

repository: netponto/netponto.github.io

collections:
  meetings:
    output: true
    permalink: /reunioes/:path/
  sessions:
    output: true
    permalink: /sessoes/:path/
  events:
    output: true
    permalink: /eventos/:path/
  members:
    output: true
    permalink: /membros/:path/
  revista-programar:
    output: true
    permalink: /revista-programar/:path/

permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
      type: meetings
    values:
      layout: page
  - scope:
      path: ""
      type: sessions
    values:
      layout: page
  - scope:
      path: ""
      type: events
    values:
      layout: page
  - scope:
      path: ""
      type: members
    values:
      layout: member-profile
  - scope:
      path: ""
      type: revista-programar
    values:
      layout: page

safe: true
markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - serve.sh

show_drafts: false
future: false

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
